services:
  web:
    build:
       context: .
    command: gunicorn main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`mazerfaker.com`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    environment:
      - TIMEOUT="600"
      - GRACEFUL_TIMEOUT="600"

  traefik:
    image: traefik:v2.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/mazerfaker.com/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.prod.toml:/etc/traefik/traefik.toml"
